version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
    - ./tmp/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 5555:8080

  # app:
  #   image: node:16
  #   working_dir: /app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./:/app
  #   command: sh -c "npx nodemon -r dotenv/config src/app.js"